name: CI
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Get ENV
        run: env
      - name: List files
        run: ls -l
      - name: check docker images
        run: docker images
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: check node version
        run: node --version
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
